### PR TITLE
Resolve error on Linux when downloading packages

### LINKED ISSUE #195: "//css_nuget" does not appear to work on Linux?
Heyo! If this is user error, sorry for wasting your time. This is a fantastic project, and I appreciate your dedication in maintaining it. I'm using it in my static site generator, [WDHAN](https://github.com/MadeByEmil/WDHAN), to implement C# plugins.

I'm trying to write such as plugin that needs two dependencies, [CodeHollow.FeedReader](https://www.nuget.org/packages/CodeHollow.FeedReader/) and [SmartReader](https://www.nuget.org/packages/SmartReader/). My code is as follows:

```
//css_nuget SmartReader
//css_nuget CodeHollow.FeedReader
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Globalization;
using System.Diagnostics;
using System.Net;
using System.IO.Compression;

public class GetArticles
{
  public void Main(string[] args)
  {
    Console.WriteLine("Plugin is ready.");
    getPublisher("http://feeds.bbci.co.uk/zhongwen/simp/rss.xml", "_bbc-zh");
  }
  public static void getPublisher(string publisherUrl, string collection)
  {
    var feed = FeedReader.Read(publisherUrl);
    int i = 0;
    foreach(var item in feed.Items)
    {
      SmartReader.Article article = SmartReader.Reader.ParseArticle(item.Link);
      if(article.IsReadable)
      {
        i++;
        article.ConvertImagesToDataUriAsync().Wait();
        string fileContents = "---\ntitle: " + item.Title + "\nlink: " + item.Link + "\ndate: " + item.PublishedDateString + "\n---\n" + article.Content;
        using (FileStream fs = File.Create("./" + collection + "/" + i + ".md"))
	{
		fs.Write(Encoding.UTF8.GetBytes(fileContents), 0, Encoding.UTF8.GetBytes(fileContents).Length);
	}
        Console.WriteLine("Processed " + item.Title + " (" + item.Link + ")");
      }
    }
  }
}
```

When running this script on Linux, I get the following output:
```bash
CSScriptLib.CompilerException: (22,16): error CS0103: The name 'FeedReader' does not exist in the current context
(26,7): error CS0246: The type or namespace name 'SmartReader' could not be found (are you missing a using directive or an assembly reference?)
(26,37): error CS0103: The name 'SmartReader' does not exist in the current context

   at CSScriptLib.RoslynEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.RoslynEvaluator.CompileCode(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.RoslynEvaluator.CompileCode(String scriptText)
   at CSScriptLib.RoslynEvaluator.LoadCode(String scriptText, Object[] args)
```

It appears that the nuget dependencies are not downloading for whatever reason. Apologies if this is intentional and it's user error.

### PR DESCRIPTION
**Pull request by ghost**
As of the latest release (1.2.1.0), the `css` command will throw the following error: 

```
Error: Specified file could not be compiled.

Could not find a part of the path '/home/user/.nuget/packages'.
```

This is because the directory `/home/user/` does not exist. Rather, `.nuget` exists within `~/` as a hidden folder.
As such, `/home/user/.nuget/packages` should be changed to `~/.nuget/packages` to resolve the error.

This resolves [https://github.com/oleg-shilo/cs-script/issues/195](https://github.com/oleg-shilo/cs-script/issues/195).

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Thanks, it appears that the path was from mono nuget infrastructure.
Txs.

**Comment by oleg-shilo** [comment]
Done, released: https://github.com/oleg-shilo/cs-script.core/releases/tag/v1.3.2.0
 
Though as I do not have right now Linux ready, it will take a bit of time to release a Linux distro.

**Comment by EmilSayahi** [comment]
Sure. Is there documentation on how I could compile this and package it? This bug is really interfering with my workflow, so if I could just compile it myself I could resume development on my own projects.

**Comment by ghost** [comment]
I've tried rewriting the Batch (.cmd) scripts as Bash, but the build process keeps throwing errors. One of particular note that I cannot figure out is the problem with `csws.csproj` not existing.

**Comment by oleg-shilo** [comment]
You don't need to compile it.  It's portable after all so you can simply bring the `cscs.dll` from the release assets and that's it.

But if you want to build the package by yourself you can read the instructions here: 
https://github.com/oleg-shilo/cs-script.core/tree/master/bin/linux/ubuntu/build

==================

Though, I've just fixed my Linux and the package is available now:
https://github.com/oleg-shilo/cs-script.core/tree/master/docs/linux/ubuntu


Install command:
```
repo=http://www.cs-script.net/cs-script.core/linux/ubuntu/; file=$(echo cs-script.core_)$(curl -L $repo/version.txt --silent)$(echo _all.deb); rm $file; wget $repo$file; sudo dpkg -i $file
```

**Pull request merged**
